server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-14239kxm.sql.tencentcdb.com:22876/ai_wechat?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: SScy7832459
    driver-class-name: com.mysql.jdbc.Driver

  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ai.wechat

wechat:
  cookie: ${COOKIE:appmsglist_action_3255439072=card; RK=SJFVqn5AN7; ptcz=cbd6b293489d3afda06089db67d1c2865b94c650d534daac8f40be73d54e1053; pgv_pvid=3308132270; pac_uid=0_f16b04907a117; _clck=o76xef|1|faz|0; _clsk=1vddvj7|1682168788019|1|1|t.clarity.ms/collect; ua_id=iJvuSKGHRC9miqBxAAAAAHt82Jyz0O09xTWMAR1u7wI=; wxuin=82169401944211; uuid=e539adc222a842647db23b37f2d3c82e; rand_info=CAESIBWYEdj110wXlOXQfMXn+BOzenFblAlH6C0l/1CATQNN; slave_bizuin=3255439072; data_bizuin=3255439072; bizuin=3255439072; data_ticket=JRC2HyykmTE58WfSinKaGyfM/LgvK6HTs9EY2vs5yeopFatPYxLkUXcgeyLPvrA3; slave_sid=b2VoQlN2OFNOQnJxRVRZRlczd2s1Q1B2RDJpTVNkNTVpT2VuV2cyREtWamtRY2dHRFYzcDVfSzJGZHpZR3BpcmJsM2VnaTY5d0o2YkhQRnFmSjZ0YnJ5N3dDNUtqd0lTZWZKbkx6a1JzdkpuN0F3clNsenJ2dkZWekI1U1VUMTdqOHl3R3QySkJJcWpJWWdO; slave_user=gh_9de8a59334a5; xid=86c3bcb50ba379a3da9cb2a3337c16b7; mm_lang=zh_CN}
  quick-reply-id: ${QUICK_REPLY_ID:500000654}
  token-id: ${TOKEN_ID:1405663667}
  access-token: ${ACCESS_TOKEN:67_pWhQyB1s2PwzldT-toBxaWOUqXyNV1UxHSsz9jxIStgH9CEinEUoGb_bGZThDa6Nvbyo6cFAjGuVy2QV0qQpMVa8zv2nuK2nZdUlsZ3QteOXYF0WCol_GR-0UDABNTdAEAHTZ}





